export const ActionTypes = {
  FETCH_FIVEDAYS: "FETCH_FIVEDAYS",
  FETCH_CURRENT: "FETCH_CURRENT",
  FETCH_LOCATIONKEY: "FETCH_LOCATIONKEY",
  ADD_FAVORITES: "ADD_FAVORITES",
  REMOVE_FAVORITES: "REMOVE_FAVORITES",
  INPUT: "INPUT",
  ERROR: "ERROR",
};
